#---------------------------
#GiHub Action part-1 - Basics
# Copyleft (c) by m 2026
#---------------------------
name: My-GitHubActions-Basics

on:
  push:
    branches:
      - main


jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing"


  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
